version: 2.1

orbs:
  splunk: kikeyama/splunk@dev:init

jobs:
  build:
    machine: true
    steps:
      - run: echo "hello world"
      - splunk/build-event:
          subject: notificatoin from main build step
          message: Successfully finisheed build to my cluster
          splunk_hec_host: ${SPLUNK_HEC_HOST}
          splunk_hec_port: 8088
          splunk_hec_protocol: http
          splunk_hec_token: ${SPLUNK_HEC_TOKEN}
          splunk_index: main


workflows:
  main:
    jobs:
      - build
      - splunk/workflow-event:
          subject: notificatoin from main workflow
          message: Successfully finisheed deploying to my cluster
          splunk_hec_host: ${SPLUNK_HEC_HOST}
          splunk_hec_port: 8088
          splunk_hec_protocol: http
          splunk_hec_token: ${SPLUNK_HEC_TOKEN}
          splunk_index: main
          requires:
            - build
